#cloud-config
hostname: pearl_demo
password: test
apt:
  sources:
    source1:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
      # keyserver: https://download.docker.com/linux/ubuntu/gpg
packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - htop
  - tree
 
